# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'QR' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QR

  target 'QRTests' do
    pod 'RNFS', :path => '../node_modules/react-native-fs'
    inherit! :search_paths
    # Pods for testing
  end

end
